name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    defaults:
      run:
      shell: bash
        working-directory: vite-project
      steps:
      - name: Fetch Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Generate Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: artifact
          path: ./dist

deploy:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - name: Setup Pages
      uses: actions/confgure-pages@v4
    - name: Download Artifact
      uses: actions/download-artifact@v4
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
```
